### PR TITLE
Compile fixes for libgit2 0f9d15493d5d8ad4353dd7beed52c9567334f6e5

### PR DESCRIPTION
**Pull request by hanwen**

### CODE REVIEW

**Comment by carlosmn** [comment]
This won't pass unless you update the submodule to the new libgit2 commit.

**Comment by hanwen** [comment]
should I base this on the 'next' branch?

**Comment by carlosmn** [comment]
Updates to libgit2 version have to happen on 'next' as 'master' is stable and only targets the releases.

**Comment by hanwen** [comment]
done (I hope)

**Comment by carlosmn** [comment]
Yep, I've merged this into `next` and pushed it up since you can't retarget PRs.

**Pull request closed without merging**
