### PR TITLE
Fix bug in Config LookupString

### PR DESCRIPTION
**Pull request by TheDahv**
A solution to `get_string called on a live config object` errors when attempting a string lookup on a config object.

### CODE REVIEW

**Comment by TheDahv** [comment]
@carlosmn, @vmg - Not sure what the best way to contact you for discussion or questions. Am I just using the Config methods wrong? I kept running into errors when doing something along these lines:

```go
path, _ := ConfigFindGlobal()
conf, _ = OpenOndisk(nil, path)
val, err = c.LookupString("foo.bar")
// err should complain about performing a lookup on a live config object
```

If that's supposed to work, then adding this snapshot method on config objects fixes the problem.

**Comment by carlosmn** [comment]
The snapshotting solves a different problem. We simply should not be using `git_config_get_string()` at all, but `git_config_get_string_buf()`. The former is something you can do if you know the lifetimes of your objects, but that's not something you can really know in Go.

**Comment by TheDahv** [comment]
@carlosmn thanks for the tip and explanation. I updated my approach to use `git_config_get_string_buf()`. I also added some tests for the other Lookup methods. Hopefully they might serve as documentation of example usage for future users of this library.

**Comment by TheDahv** [comment]
@carlosmn any further feedback or shall I just wait until more time frees up for you?

**Comment by carlosmn** [comment]
Just to clean up the history here. This PR still contains commits to add and remove snapshotting capabilities. If all you're aiming for is to get string lookups to work, that's the only one it should have.

**Comment by TheDahv** [comment]
Sorry, got caught up for a few days. Commits cleaned up and squashed.

**Pull request merged**
