### PR TITLE
Switch over the version constraints to v0.28

### PR DESCRIPTION
**Pull request by suhaibmujahid**

### CODE REVIEW

**Comment by hackworks** [comment]
Request merging this change, it is blocking me from upgrading to libgit2 0.28 across Python and Go

**Comment by lhchavez** [comment]
Thanks for the patch!

an identical PR was merged earlier today (#515), so closing this one since it would conflict with HEAD

**Comment by suhaibmujahid** [comment]
@lhchavez thank you for looking into this pull request.

I want to let you know that this fix still not merged to the `v28` branch. Yes ((#515) have the same fix, but it was merged to the `master`.

**Comment by lhchavez** [comment]
> @lhchavez thank you for looking into this pull request.
> 
> I want to let you know that this fix still not merged to the `v28` branch. Yes ((#515) have the same fix, but it was merged to the `master`.

branches are hard -_-. approved, will merge as soon as Travis says we are good to go.

**Comment by QuLogic** [comment]
There really should be a new tag with this fix, since the last one cannot build as is.

**Comment by lhchavez** [comment]
> There really should be a new tag with this fix, since the last one cannot build as is.

[v0.28.4.1](https://github.com/libgit2/git2go/releases/tag/v0.28.4.1) is now live!

**Pull request merged**
